### ISSUE TITLE
Question: does git-revise preserve merge commits

### ISSUE THREAD

**Issue by nafg** [mystor/git-revise#107]
`git rebase` by default does not preserve merge commits. IIUC there are two opt-in merge-preserving modes, the deprecated `--preserve-merges` and the newer `--rebase-merges`.

What is `git-revise`'s behavior?

**Comment by mystor** [comment]
`git-revise` produces an error if you try to perform a modification which would impact merge commits

**Comment by nafg** [comment]
It would be for an ancestor of a merge commit, without -i

**Comment by nafg** [comment]
@mystor thanks
