### ISSUE TITLE
[feature request] interactively select commit to revise

### ISSUE THREAD

**Issue by RalfJung** [mystor/git-revise#130]
It is fairly common for me to want to revise some specific commit that I know is closed to the tip of the current branch, but I don't remember exactly how many commits in the past it is... so I always do `git log`, count the number of commits, and then to `git revise HEAD~N` (or I copy-paste the commit id from `git log`).

It would be really nice if I could avoid the `git log` interaction, and instead have `git revise` present me with a menu showing the most recent commits and their messages, and interactively letting me select (via the arrow keys or so) which commit to revise.

**Comment by alerque** [comment]
While it might be nice for `git revise` to support this, if you want the feature *today* you can reach for [`git smash`](https://github.com/anthraxx/git-smash) instead which is designed around that exact workflow out of the box. It uses `skim` to interactively select previous commits to amend.

**Comment by Manishearth** [comment]
we could potentially build a similar mode that works if `skim` is installed

**Comment by RalfJung** [comment]
Thanks, I did not know about `git smash`. Its documentation is rather sparse though. Does it behave like `git revise` in terms of not touching files and ensuring that the resulting tree is unchanged?

**Comment by alerque** [comment]
No, the workflow is more like `git absorb` where it creates fixup commits with an *option* to rebase. You could pain it with `git revise` to stuff the fixups in the actual commits without touching the file system. Basically `git smash && git revise --autosquash` is the workflow you're looking for.

**Comment by RalfJung** [comment]
Oh, autosquash can squash things into previous (not the latest) commit? I am learning so many new tricks today.^^

**Comment by krobelus** [comment]
I just have these bindings in my tigrc (remotely inspired by Magit)

```
bind generic ava >git revise --reauthor %(commit)
bind generic avc >git revise --cut %(commit)
bind generic avE >git revise --interactive --edit %(commit)^
bind generic ave >sh -c 'git revise --interactive --edit "$(fork-point.sh)"'
bind generic avf >git revise %(commit)
bind generic avi >git revise --interactive %(commit)^
bind generic avI >git revise --interactive %(commit)^ --edit
bind generic avu >sh -c 'git revise --interactive "$(fork-point.sh)"'
bind generic avw >git revise --edit %(commit)
bind generic aco >sh -c 'git-autofixup "$(fork-point.sh)" --exit-code; test $? -lt 2 && GIT_SEQUENCE_EDITOR=true git revise --interactive --autosquash "$(fork-point.sh)"'
```

where `fork-point.sh` is a shell script that finds the mege-base between HEAD and the upstream branch (even during an interactive rebase)

```sh
#!/bin/sh

upstream='@{upstream}'

if test -d .git/rebase-merge; then
	branch=$(sed "s,.*/,," .git/rebase-merge/head-name)
	remote=$(
		git config branch."$branch".remote ||
		git config branch."$branch".pushRemote ||
		git config remote.pushDefault ||
		echo origin
	)
	upstream="$remote/$branch"

	if ! git rev-parse "$upstream" >/dev/null 2>&1; then
		upstream="$remote/$(basename "$(git config branch."$branch".merge)")"
	fi
fi

git merge-base HEAD "$upstream"
```

**Comment by Manishearth** [comment]
I tend to use triple-dots for figuring out fork point ranges (`origin/main...`) which works pretty well in most situations

**Comment by krobelus** [comment]
right but the script doesn't know whether it's `origin/main` or `origin/master` etc. so it takes the a detour. I wish there was a shorthand for this

**Comment by RalfJung** [comment]
AFAIK `HEAD@{u}` is upstream of the current branch? I didn't know about `...` though, nice.

**Comment by Manishearth** [comment]
@krobelus ah i have a different git alias for that, `getmain = "!f() { if (git rev-parse master 1>/dev/null 2>/dev/null); then echo master; else echo main; fi }; f"`

**Comment by krobelus** [comment]
yeah, `@{u}` will work unless you are in an interactive rebase (where it means something else)

**Comment by RalfJung** [comment]
Awesome, I now have this in my tigrc
```
bind generic + <git revise %(commit)
```
and it seems to work perfectly. :)
