### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by leahneukirchen** [mystor/git-revise#14]
Lovely tool, I'm packaging it for Void Linux.

Please add a LICENSE with a copyright line file if it's MIT-licensed.

**Comment by alerque** [comment]
It [already has a LICENSE](https://github.com/mystor/git-revise/blob/master/LICENSE) file.

**Comment by leahneukirchen** [comment]
That's not included in the Pypi tarball... :(

**Comment by alerque** [comment]
No, but the tarball does include the meta data (in two different places) that specifies the license and author, as documented by Python distutils. Why is that not enough, esp for a standard license like MIT?

**Comment by leahneukirchen** [comment]
Because the license says "The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software."
