### ISSUE TITLE
MacOs install

### ISSUE THREAD

**Issue by damiendube** [mystor/git-revise#17]
I'm on a pretty vanilla MacOs Mojave.

I had to add python3 using brew since my system only had python2 by default
`brew install python3`

Installed using a slightly different command than the one in the doc
`pip3 install --user git-revise`

No the modules is installed but when I run `git revise` I get this error.
`git: 'revise' is not a git command. See 'git --help'.`

**Comment by romac** [comment]
Try adding `$HOME/Library/Python/3.7/bin` to your `PATH`.

**Comment by zxaos** [comment]
git-revise is now also available directly via brew
`brew install git-revise`
