### ISSUE TITLE
Document patch stack workflow

### ISSUE THREAD

**Issue by cflewis** [mystor/git-revise#18]
The [blog post](https://mystor.github.io/git-revise.html) refers to using `git revise` in a patch stack workflow (e.g. Gerrit). However, neither the blog post nor the man page describes what the workflow actually is.

Given commits
```
A
B
C - HEAD
```

and my reviewer wants changes to commit `B`, I find myself needing to perform a `git rebase -i / [hack hack] / git commit / git rebase --continue` (and usually screw it up at some stage if I am honest with myself). 

How do I use `git-revise` to edit commit B? Can this be added to the documentation?

**Comment by Manishearth** [comment]
`git add <files>; git revise B`

**Comment by cflewis** [comment]
This is almost complete but not quite :)

If I need to make changes to commit B, how do I get the files at the state of commit B in the first place?

`git co B; [hack hack] git add <files>; git revise B`?

**Comment by Manishearth** [comment]
You can use `git revise -i` with `edit`, the same way you would with rebase.

The whole point of the tool is that you don't need to check out other commits.

**Comment by cflewis** [comment]
Got it. Thanks!

**Comment by cflewis** [comment]
Wait! `git revise -i` has no `edit` option :/

**Comment by alerque** [comment]
@cflewis It sounds to me like your use case isn't appropriate for this tool anyway. The entire point of the tool (as I understand it) is to revise a previous commit by adding something from the staging environment and patch it onto a previous commit _WITHOUT_ having to change the working directory to that state first or during the process.

If you want to have your files restored to the state of a previous commit before working on them then a regular `git rebase` workflow might be for you. Use `git revise` when you want to patch something into a previous commit without backtracking your working directory to the former state.

**Comment by cflewis** [comment]
Sounds good, thanks for the help :+1:
