### ISSUE TITLE
git config core.commentchar is ignored

### ISSUE THREAD

**Issue by gerboengels** [mystor/git-revise#22]
First of all, great tool.

I have set `git config --global core.commentchar ';'`, so comments in, for example, the interactive rebase TODO editor aren't prefixed with `#` but with `;`. `git revise -i` ignores the settings and still shows `#` (which is unfortunate when editing commit messages with `git revise -ie`, since our commit messages start with `#<ticket number>`).

Could `git revise` respect the set commentchar?

**Comment by mystor** [comment]
Shouldn't be too hard to fix. For some reason I had it in my head that `git-revise` already supported that config, but I suppose it doesn't.

The correct comment char just needs to be used here:
https://github.com/mystor/git-revise/blob/eb832a76a1455b13608b9b2369c2e55fa2800c82/gitrevise/utils.py#L98
and stripped here:
https://github.com/mystor/git-revise/blob/eb832a76a1455b13608b9b2369c2e55fa2800c82/gitrevise/utils.py#L73

That should cover pretty much everywhere comments are used.

**Comment by lilyball** [comment]
Note that `core.commentchar` supports the value `auto` that selects a character that's not already the beginning of any line of the message. I don't know what the actual logic it uses is though, the documentation doesn't elaborate.

**Comment by mystor** [comment]
Looks like the logic git uses for `core.commentchar=auto` is here: https://github.com/git/git/blob/9c9b961d7eb15fb583a2a812088713a68a85f1c0/builtin/commit.c#L631-L659

Effectively considers each character in `"#;@!$%^&|:"`, and then walks through each line & checks if it starts with one of them, eliminating it from the running.
