### ISSUE TITLE
--ref flag should accept unambiguous abbreviated refs

### ISSUE THREAD

**Issue by lilyball** [mystor/git-revise#26]
It seems the `--ref` flag requires a fully-specified ref. This is a bit weird. I should be able to specify an abbreviated ref which it will expand for me, e.g. `git revise --ref feature/foo` instead of `git revise --ref refs/heads/feature/foo`.

Because this flag requires specifying an existing ref, this will not change the behavior of any existing legal invocations, it will only make it accept more values than it used to.

Curiously, the output suggests that part of the command does interpret it as an abbreviated ref, but the rest doesn't. In particular, `--ref featA` gives me the output

```
Applying staged changes to 'HEAD~3'
5e82a2e300e2 b
603f745f9635 c
Updating featA (736a814269625c169cf7123d0b3c3d49d7bc5126 => 603f745f96350564289ac6234d4476cc2b0d3ae8)
fatal: update_ref failed for ref 'featA': cannot lock ref 'featA': unable to resolve reference 'featA'
```

So it's doing all of the work with the correct ref, including printing the old and new SHAs, but the only failing at the final `update_ref` invocation.

**Comment by mystor** [comment]
Thanks for the report. I tried poking at this a bit, but it appears that `git` doesn't have a great way to resolve an abbreviated ref to a full one without following symbolic refs.

We might be able to get away with running `git rev-parse --symbolic-full-name $REF` on the ref provided at the command-line. Unfortunately this will deref `HEAD` to the current feature branch at the time (e.g. `refs/heads/master`). That might be OK though.

**Comment by lilyball** [comment]
If you need to distinguish them, you could run `git symbolic-ref "$REF"` first. If it's a symbolic ref, that'll print what it points to, otherwise it will fail with an error.
