### ISSUE TITLE
Add `exec` command to interactive mode

### ISSUE THREAD

**Issue by lilyball** [mystor/git-revise#28]
It would be nice if the interactive mode had an `exec` command. This would be executed with the working directory pointing at an empty temporary directory, but environment variables set up appropriately such that git commands will manipulate the git index. This way I can do arbitrary operations that don't rely on a working directory.

For example, if I want to reset the author of a single commit, I could insert the line

```
exec git commit --amend -C HEAD --reset-author
```

There's also an argument for having another variant of this that operates out of a workdir, but the default should be index-only.

If multiple `exec` commands are given they should run from the same temporary directory. The temporary directory should also only be cleaned up after the whole operation is complete. This means that without the workdir version I could approximate it by saying something like

```
exec git --work-tree=. checkout -- .
exec echo foo > foo
exec git --work-tree=. commit --amend -C HEAD foo
```

**Comment by alerque** [comment]
While on the one hand I admit I would probably use this if it existed, isn't it also bloat? This functionality already exists. In the case of your author example you could accomplish this with `git filter-branch --env-filter`. Adding more and more ways to do the same thing starts reminding me of `perl`, which is great if you really have your head around the language and an absolute nightmare for anybody learn or work with other people's code.

The lack of a working directory would also be somewhat of a surprise and even knowing about needing to only use commands that were index-only I would still make the mistake of thinking I could use shell functions at that point. I would at least name this `exec-index` or something else as a reminder that it is not a drop in replacement for `rebase`'s `exec`.

**Comment by lilyball** [comment]
If I'm only modifying env then yes I can do `git filter-branch --env-filter`.

The motivating example here is something like

```
pick 5152786f70f2 b
fixup c08daa5ef3d5 fixup! b
pick 736a81426962 c
exec git update-ref refs/heads/foobar HEAD
pick ce817c55b54c d
pick e7b6185cdd59 e
```

I can't do this with `git filter-branch` because I'm modifying the diffs introduced by individual commits. You can't do this with `filter-branch`.

> The lack of a working directory would also be somewhat of a surprise and even knowing about needing to only use commands that were index-only I would still make the mistake of thinking I could use shell functions at that point.

I'm not sure what you mean; why wouldn't you be able to use shell functions? You have a working directory, just not a checked-out work tree.

**Comment by Manishearth** [comment]
Git revise is fully in-memory, it doesn't run the commands one by one, so it can't stop and execute. This is precisely what sets it apart from git rebase -- by being fully in memory one doesn't have to worry about the working directory getting touched, or the slowing down due to the application of commits.

Note that revise doesn't have an "edit" feature either. This is at least possible to implement without making revise like rebase, but it's still not easy.

**Comment by lilyball** [comment]
It's fully in-memory, but I don't know what you mean by "it doesn't run the commands one by one".

That said, after thinking about what I want to say, it occurs to me that one of the points of git-revise is that the final *tree* is identical to what you start with (or at least, the final index), and the existence of an `exec` command throws that for a loop because I could trivially execute something that modifies the tree.

Given that, I'm going to abandon this and focus my evangelism towards the more targeted commands like `ref` (see #25).

**Comment by Manishearth** [comment]
> It's fully in-memory, but I don't know what you mean by "it doesn't run the commands one by one".

It doesn't run the command, update the working tree, and then run the next one, it applies them all in one go, after checking idempotence.

> That said, after thinking about what I want to say, it occurs to me that one of the points of git-revise is that the final tree is identical to what you start with (or at least, the final index),

This requirement _could_ be reduced, in case of resolved merge conflicts (which are at the implementation level similar to having an `edit` command) any changes leftover get applied to the index, and we could instead un-apply those. The UX around this has to be improved -- the reason the merge conflict thing is there is that _ideally_ that never happens, and when it happens it's a mistake that you can fix by `revise`ing the remaining index changes. But an actual `edit`  and support for dropping commits could be added by relaxing this requirement, if we can come up with good UX around it.

**Comment by lilyball** [comment]
> It doesn't run the command, update the working tree, and then run the next one, it applies them all in one go, after checking idempotence.

Right, but it could do this to a subset of the todo list, then stop, set up an empty temp dir and a fresh index file, then run the shell command from that dir with the correct environment variables set, etc.

The biggest complication here is the need to set up an entire new working tree, in order to have a separate `HEAD`. Something like `git worktree add --no-checkout`, though I don't know if the worktree could be hacked up to avoid modifying the real git dir (`git worktree` modifies `.git/worktrees`) since this is just a short-lived temporary directory.

> But an actual `edit` and support for dropping commits could be added by relaxing this requirement, if we can come up with good UX around it.

If you think it's doable, then I'm happy to reopen this issue. It still seems like a useful general-purpose utility to have.

**Comment by Manishearth** [comment]
I think `edit` is doable, not `exec`

**Comment by lilyball** [comment]
Oh yes you did say `edit`. I'm not really sure why you think `edit` is doable but not `exec` though; both require setting up the new worktree, it's just the former drops you into an interactive shell and the latter runs a one-line script.

**Comment by Manishearth** [comment]
Oh, no, with edit you can prompt for the files you want to edit, or you only get to edit files that the commit (or series) is changing. I'm not imagining it being identical to rebase.

**Comment by mystor** [comment]
Running a custom command during the rebase operation is technically possible, but you wouldn't have access to an up-to-date working directory or index file. Instead, the program would probably need to act as a "Commit Transformer", so it'd be fed a SHA1 with the commit being applied, and could generated a new SHA1 for the new commit to use instead.

Unfortunately, there aren't really any useful git commands to perform that kind of transformation right now, so it'd be quite difficult to use..
