### ISSUE TITLE
Edit multiple commit messages simultaneously

### ISSUE THREAD

**Issue by mystor** [mystor/git-revise#3]
It would be nice to be able to edit a stack of messages at the same time to ensure that an entire commit stack is consistent. Currently I often do this with my [git-rmsg](https://github.com/mystor/git-rmsg) project, but it might make sense to integrate into this project.

**Comment by Manishearth** [comment]
Perhaps just create a "reword-in-place" step (needs better name) that uses the edited message from the message string after it?

But that doesn't handle long messages hm.

Or a fake step that you write at the beginning that lets you do this.

**Comment by mystor** [comment]
I wonder if it could be `git revise -ie` and would do the full pick etc. Setup but with full commit messages after each pick line...

**Comment by mystor** [comment]
`git revise -ie` works now as-of 84923b11d06ec15b8f2a8efe4b8423995125bf16
