### ISSUE TITLE
invalid value: Commit bac38ea0... has 2 parents

### ISSUE THREAD

**Issue by saschanaz** [mystor/git-revise#32]
I tried `git revise upstream/master` on my local gecko-dev clone and got this:

```
invalid value: Commit bac38ea0eacfc9f319de142aa6ca3483dcdce780 has 2 parents
```

That's https://github.com/mozilla/gecko-dev/commit/bac38ea0eacfc9f319de142aa6ca3483dcdce780, but not sure why it is a problem. Can I get some help?

**Comment by mystor** [comment]
When you run `git revise FOO`, it will try to update the commit named by `FOO` with the changes currently staged in your index. If you wanted to produce a `git rebase -i`-style editing interface, you probably want `git revise -i`.

If you mean to do a rebase to update your local copy to match upstream, you don't want to use `git revise`. It's not a replacement for that functionality of rebase. In general, if the final state of the checkout changes, you need rebase, not revise.

**Comment by saschanaz** [comment]
Ah, thanks! It seems I had some misunderstanding about `git revise`.
