### ISSUE TITLE
Feature request: Say which patch failed when editing a conflict

### ISSUE THREAD

**Issue by anordal** [mystor/git-revise#45]
A useful feature of `git rebase -i` is that it says which commit failed to apply when there is a conflict:

    Could not apply badbeef... Commit bla bla

To me, this is essential information, because the editing is after all not of the end result, but some intermediate commit – you need to know which commit you're editing. Even if you can guess it, you don't want to take chances here, because of how easily this can make a tangled mess of the commits.

Git rebase also repeats the commit title inside the editable git conflict (whereas revise just puts "incoming" here). That would also suffice, though I really don't like the userfriendlyness of standard git conflicts. Thus why I suggest printing a message in plain English.

Perhaps the git conflict is the better place for this info, but then I would say the real problem is the readability of standard git conflicts: They look too much like a conflict between equals, and presents which two commits it came from, when what matters is which one commit you're editing. They really should just say `You are editing commit "Commit bla bla"`. If this is fixable, I would say you don't need the message, because then, a preview would hint even better to the user whether to edit or abort.

**Comment by mystor** [comment]
The part where the commit title isn't inside of the editable git conflict should be really easy to fix. The names used by `git-revise` are provided here: https://github.com/mystor/git-revise/blob/7db23e2f708527d52a8b5c72dc33b079c6e16c0d/gitrevise/merge.py#L34

A fix to that part of this issue should only require adding commit details into the strings from that tuple.

The same information could also be printed out when the conflict itself is reported. The labels which were provided at the previously noted lines should contain the relevant metadata, and could theoretically be printed out before prompting the user here: https://github.com/mystor/git-revise/blob/7db23e2f708527d52a8b5c72dc33b079c6e16c0d/gitrevise/merge.py#L204

I'd be open to a PR which adds this extra metadata to conflict files.
