### ISSUE TITLE
Breaks on non-ASCII branch names

### ISSUE THREAD

**Issue by chris-morgan** [mystor/git-revise#47]
I put `→` into a branch name, because I like doing things like that from time to time, and git-revise 0.5.0 didn’t like it:

> invalid value: 'ascii' codec can't encode character '\u2192' in position 29: ordinal not in range(128)

(At first I thought this was because of a commit message, but when I modified tui.py to stop it suppressing the backtrace (*please* don’t unconditionally suppress backtraces like that!), I realised it was the branch name that did it.)

My initial reaction is that all mentions of `"ascii"` should be changed to `"utf-8"` in odb.py.

**Comment by mystor** [comment]
Good thing to note! Most uses of the `"ascii"` decode style are for values which are known to be ASCII-only, such as sha1 hashes or object type tags, however there is one place where the wrong value is used, which is for refs.

Specifically, I believe this is the use which needs to be changed to "utf-8":
https://github.com/mystor/git-revise/blob/f8889aed6d1121572d13a0ae145aa558c1663eb3/gitrevise/odb.py#L307
