### ISSUE TITLE
Removed lines are not treated like index lines as revise -i suggests

### ISSUE THREAD

**Issue by totph** [mystor/git-revise#52]
Calling `git revise -i HEAD~3` and removing a line to move it to the index does not work.

The help text in the `git-revise-todo` buffer says:

`# If a line is removed, it will be treated like an 'index' line.`

but removing a line (even the last) shows an error:

`invalid value: Unexpected commits missing from TODO list`.

Maybe it should also be mentioned that `index` lines must be last.

**Comment by mystor** [comment]
Thanks for the report. That's a mistake in the documentation from an earlier version which did treat missing commits as 'index' lines. 

We should definitely update the documentation to be correct here.

https://github.com/mystor/git-revise/blob/162ac90cba010a0f90f2290bf267d130466417d6/gitrevise/todo.py#L198-L212

**Comment by totph** [comment]
Ah, not a new feature :)

See #56

**Comment by mystor** [comment]
This has been fixed since #56
