### ISSUE TITLE
fixup! commits are reversed during interactive revise calls

### ISSUE THREAD

**Issue by bogdanb** [mystor/git-revise#69]
If I have a “base” commit and then several “fixup! base” commits, running an interactive revise will prepare the commit list in the wrong order.

For example, if the commit list is:

    abc123 base commit
    abc456 fixup! base commit
    abc789 fixup! base commit

Then running `git revise -i abc123~` will open an editor with these contents:

    pick abc123 base commit
    fixup abc789 fixup! base commit
    fixup abc456 fixup! base commit

It should have generated this instead:

    pick abc123 base commit
    fixup abc456 fixup! base commit
    fixup abc789 fixup! base commit

I suspect the [this commit](https://github.com/mystor/git-revise/commit/837c779f17522fca0eaf4f8b59f4beefcef2496f) is the culprit.

**Comment by mystor** [comment]
That bug was fixing another ordering issue which would occur when a fixup-of-fixup is being performed, and apparently regressed this.

This probably needs to be fixed by cleaning up the reordering code to track groups of entries being moved around, rather than the naive approach currently taken.

**Comment by bogdanb** [comment]
Any hints on how to generate and use a modified binary? (I’m currently using the one `pip install` set up.) I _might_ have time to look at the code and submit a pull request, but I was hoping not to spend a day learning all the tooling.

**Comment by mystor** [comment]
OTTOMH you should be able to set up a dev environment by cloning the repo, and running `pip install --editable path/to/checkout`. This should install it like normal, but referencing the existing sources, so changes to them should be reflected immediately.

You can then run tests by with `tox`, and format using `black` (both of which will need to be installed).
