### ISSUE TITLE
Consider bumping the minimum python version to 3.8

### ISSUE THREAD

**Issue by mystor** [mystor/git-revise#90]
When `git-revise` was originally written, it targeted Python 3.6, as that is the version installed by default on Ubuntu 18.04 LTS. The latest Ubuntu LTS has been 20.04 for ~a year, which comes with Python 3.8 installed.

It might be nice to bump the minimum Python version to match this new LTS, which would reduce the number of configurations to test & allow using newer features.

**Comment by Manishearth** [comment]
This sounds like a good idea

**Comment by krobelus** [comment]
I sometimes need to use an openSUSE 15.2 system which is still on Python 3.6, probably until June :roll_eyes: 
I guess if we want to be on the safe side, either bump the version now and wait a bit with the next release, or bump right after the next release.

**Comment by alerque** [comment]
A bump like this is usually much better done right *after* a release cycle than before. That gives distros something to work with with the best available version they can still support. I'm in favor of this dependency bump happening, I just suggest tagging a release just before it happens for the sake of distro packagers in a bind.

**Comment by mystor** [comment]
We can definitely cut a release before we do the version bump
